In [1]:
""" 
Pandas is a powerful and popular open-source Python library primarily used for
data manipulation cleaning and analysis.
•1.  ⁠It provides easy to use data structures and functions making it an essential tool in
the field of data science and analysis.
2. Its name is derived from Panel Data, which refers to multidimensional structured
datasets.
"""

' \nPandas is a powerful and popular open-source Python library primarily used for\ndata manipulation cleaning and analysis.\n•1.  \u2060It provides easy to use data structures and functions making it an essential tool in\nthe field of data science and analysis.\n2. Its name is derived from Panel Data, which refers to multidimensional structured\ndatasets.\n'

In [2]:
import pandas as pd
import numpy as np
print("Pandas and Numpy imported succesfully")

Pandas and Numpy imported succesfully

In [3]:
#Series and dataframe basics

In [4]:
import pandas as pd
import numpy as np
s=pd.Series([10,"abc",30])
#s=pd.Series([10,20,30],index=['a','b','c'])
print("series:")
print(s)

series:
0     10
1    abc
2     30
dtype: object

In [5]:
s=pd.Series([10,"abc",30])
s=pd.Series([10,20,30],index=['a','b','c'])
print("series:")
print(s)

series:
a    10
b    20
c    30
dtype: int64

In [6]:
import pandas as pd
data={
    'Name':['Anna','Ben','Cathy'],
    'Marks':[88,92,79],
    'Gender':['F','M','F']
}
stu=pd.DataFrame(data)
print(stu)

    Name  Marks Gender
0   Anna     88      F
1    Ben     92      M
2  Cathy     79      F

In [7]:
df=pd.read_csv('winequality.csv')               #d.head()      Give top 5 rows
df.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [8]:
df=pd.read_csv('winequality.csv')               #d.head()      Give top 5 rows
df.tail()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [9]:
df=pd.read_csv('winequality.csv')               #Give table structer
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  6497 non-null   object
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB

In [10]:
df=pd.read_csv('winequality.csv')               #df.describe()      Give min,max,mean,etc values
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,6487.000000,6489.000000,6494.000000,6495.000000,6495.000000,6497.000000,6497.000000,6497.000000,6488.000000,6493.000000,6497.000000,6497.000000
mean,7.216579,0.339691,0.318722,5.444326,0.056042,30.525319,115.744574,0.994697,3.218395,0.531215,10.491801,5.818378
std,1.296750,0.164649,0.145265,4.758125,0.035036,17.749400,56.521855,0.002999,0.160748,0.148814,1.192712,0.873255
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,5.000000
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,6.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000

In [11]:
df=pd.read_csv('winequality.csv')               #df.shape    Give total number of rows and columns of table
df.shape

(6497, 13)

In [12]:
df=pd.read_csv('winequality.csv')
print("Columns:",df.columns)

Columns: Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [13]:
df=pd.read_csv('winequality.csv')
print("Columns:",df.index)

Columns: RangeIndex(start=0, stop=6497, step=1)

In [14]:
df=pd.read_csv('winequality.csv')
print("Columns:",df.dtypes)

Columns: type                     object
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [15]:
#Selecting and filtering data
import pandas as pd
data={
    'Name':['Anna','Ben','Cathy'],
    'Marks':[88,92,79],
    'Gender':['F','M','F']
}
stu=pd.DataFrame(data)
print(stu)

    Name  Marks Gender
0   Anna     88      F
1    Ben     92      M
2  Cathy     79      F

In [16]:
print(stu['Marks'])

0    88
1    92
2    79
Name: Marks, dtype: int64

In [17]:
print(stu['Name'])

0     Anna
1      Ben
2    Cathy
Name: Name, dtype: object

In [18]:
print(stu['Gender'])

0    F
1    M
2    F
Name: Gender, dtype: object

In [19]:
#Row access
print(stu.iloc[1])          #iloc=index location

Name      Ben
Marks      92
Gender      M
Name: 1, dtype: object

In [20]:
print(stu.loc[1])           #location(Default index)

Name      Ben
Marks      92
Gender      M
Name: 1, dtype: object

In [21]:
print(stu.iloc[1,0])         #integer position based

Ben

In [22]:
print(stu.loc[1,'Name'])      #Label position based

Ben

In [23]:
print(stu.iloc[1,1])

92

In [24]:
print(stu.loc[1,'Marks'])

92

In [25]:
print("\nStudents with marks>85\n")
print(stu[stu['Marks']>85])

Students with marks>85

   Name  Marks Gender
0  Anna     88      F
1   Ben     92      M

In [26]:
#Adding or modifying column
stu['Passed']=stu['Marks']>=85
print(stu)

    Name  Marks Gender  Passed
0   Anna     88      F    True
1    Ben     92      M    True
2  Cathy     79      F   False

In [27]:
#Handling missing data
import numpy as np
stu.loc[1,'Marks']=np.nan
print("With NaN:")
print(stu)

With NaN:
    Name  Marks Gender  Passed
0   Anna   88.0      F    True
1    Ben    NaN      M    True
2  Cathy   79.0      F   False

In [28]:
print(stu.isnull())

    Name  Marks  Gender  Passed
0  False  False   False   False
1  False   True   False   False
2  False  False   False   False

In [29]:
print(stu.isnull().sum())

Name      0
Marks     1
Gender    0
Passed    0
dtype: int64

In [30]:
print("Fill NaN value with 0")
print(stu.fillna(0))

Fill NaN value with 0
    Name  Marks Gender  Passed
0   Anna   88.0      F    True
1    Ben    0.0      M    True
2  Cathy   79.0      F   False

In [31]:
print("Drop NaN rows")
print(stu.dropna())

Drop NaN rows
    Name  Marks Gender  Passed
0   Anna   88.0      F    True
2  Cathy   79.0      F   False

In [32]:
#Basic statistics & Aggregation
print("Mean:",stu['Marks'].mean())
print("Max:",stu['Marks'].max())
print("Min:",stu['Marks'].min())
print("Std:",stu['Marks'].std())
print("Sum:",stu['Marks'].sum())

Mean: 83.5
Max: 88.0
Min: 79.0
Std: 6.363961030678928
Sum: 167.0

In [33]:
print("Fill NaN value with 0")
stu2=stu.fillna(0)
print(stu2)
print("Drop NaN rows")
print(stu.dropna())

Fill NaN value with 0
    Name  Marks Gender  Passed
0   Anna   88.0      F    True
1    Ben    0.0      M    True
2  Cathy   79.0      F   False
Drop NaN rows
    Name  Marks Gender  Passed
0   Anna   88.0      F    True
2  Cathy   79.0      F   False

In [34]:
print("Sorted by marks")
print(stu.sort_values('Marks',ascending=False))
print("Group by gender")
print(stu.groupby('Gender')['Marks'].mean())

Sorted by marks
    Name  Marks Gender  Passed
0   Anna   88.0      F    True
2  Cathy   79.0      F   False
1    Ben    NaN      M    True
Group by gender
Gender
F    83.5
M     NaN
Name: Marks, dtype: float64

In [35]:
"""Create a dataframe with student name,subject,and score and add a column grade based on score(>90=A,>80=B,else c)fill any missing score with average group by subject and get average score sort all students by score in descending order"""

'Create a dataframe with student name,subject,and score and add a column grade based on score(>90=A,>80=B,else c)fill any missing score with average group by subject and get average score sort all students by score in descending order'

In [36]:
import pandas as pd
import numpy as np
detail={
    'Name':['Amrit','Ashish','Tarun','Saksham'],
    'Subject':['Physics','Chemistry','Math','IoT'],
    'Score':[95,82,np.nan,76]
}
det=pd.DataFrame(detail)
print("Final DataFrame:")
print("\n")
print(det)

#Fill missing score with average
det['Score']=det['Score'].fillna(det['Score'].mean())

#Assign Grade
det['Grade']=det['Score'].apply(lambda x:'A' if x>90 else('B' if x>80 else 'C'))

#Group by subject
print("\n")
print("Grouped by subject:")
print("\n")
grp=det.groupby('Subject')['Score'].mean()
print(grp)

#Sort by marks
print("\n")
print("Sorted by marks:")
print("\n")
print(det.sort_values('Score',ascending=False))

Final DataFrame:


      Name    Subject  Score
0    Amrit    Physics   95.0
1   Ashish  Chemistry   82.0
2    Tarun       Math    NaN
3  Saksham        IoT   76.0


Grouped by subject:


Subject
Chemistry    82.000000
IoT          76.000000
Math         84.333333
Physics      95.000000
Name: Score, dtype: float64


Sorted by marks:


      Name    Subject      Score Grade
0    Amrit    Physics  95.000000     A
2    Tarun       Math  84.333333     B
1   Ashish  Chemistry  82.000000     B
3  Saksham        IoT  76.000000     C

In [37]:
#Normal function without lambda
def assign_grd(score):
    if score>90:
        return 'A'
    elif score>80:
        return 'B'
    else:
        return 'C'
det['Grade1']=det['Score'].apply(assign_grd)
print(det)

      Name    Subject      Score Grade Grade1
0    Amrit    Physics  95.000000     A      A
1   Ashish  Chemistry  82.000000     B      B
2    Tarun       Math  84.333333     B      B
3  Saksham        IoT  76.000000     C      C